In [1]:
my_list =[1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
print("arange is useful to create array")

arange is useful to create array


In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [20]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
print("linspace creates the evenly space between the two given starts and ends")

linspace creates the evenly space between the two given starts and ends


In [27]:
print('to create identity matrix')

to create identity matrix


In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.random.rand(5)

array([0.80122457, 0.52513288, 0.09814681, 0.88196543, 0.39913691])

In [31]:
np.random.rand(5,5)

array([[0.02854294, 0.72241228, 0.9909134 , 0.97313119, 0.96332925],
       [0.38087755, 0.93387509, 0.04509934, 0.85122755, 0.19006334],
       [0.8345369 , 0.45001161, 0.27292204, 0.39240663, 0.32898654],
       [0.8388973 , 0.85580185, 0.08592927, 0.07392662, 0.69567161],
       [0.79546518, 0.11189895, 0.14877596, 0.79316805, 0.33654389]])

In [32]:
np.random.randn(2)

array([-2.00702562,  0.17031772])

In [33]:
np.random.randn(4,4)

array([[-0.12839848,  3.05695157,  1.43048733,  0.63717115],
       [ 1.28817457,  1.30906787,  1.19385222,  0.49476976],
       [ 0.08544855,  2.52843992,  0.83316012,  1.72013907],
       [-1.97954866,  0.07099708,  1.67724417, -0.04046395]])

In [38]:
np.random.randint(1,100) 

99

In [36]:
np.random.randint(1,100,10)

array([26, 91, 74, 76, 38,  6,  2, 17, 37, 65])

In [39]:
print("the code above creates the random integers ... np.random(1,100)")

the code above creates the random integers ... np.random(1,100)


In [40]:
arr = np.arange(25)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
ranarr =np.random.randint(0,50,10)

In [43]:
ranarr

array([ 1, 27, 20,  3, 33, 31, 37, 39, 46,  2])

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
ranarr

array([ 1, 27, 20,  3, 33, 31, 37, 39, 46,  2])

In [52]:
ranarr.max()

46

In [53]:
ranarr.min()

1

In [54]:
ranarr

array([ 1, 27, 20,  3, 33, 31, 37, 39, 46,  2])

In [60]:
ranarr.argmax()

8

In [61]:
ranarr.argmin()

0

In [65]:
arr.shape

(25,)

In [66]:
arr = arr.reshape(5,5)

In [67]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
arr.shape

(5, 5)

In [69]:
arr.dtype

dtype('int32')

In [72]:
from numpy.random import randint


In [73]:
randint(2,10)

7